### ISSUE TITLE
Improve gihub.io pages

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#68]
After merging #65 , we need to:

- [x] #81
- [x] make sure that the CI and all contributors badges show up in the Home page. 
- [X] Add a button that says "report a bug" that points at https://github.com/ARM-software/acle/issues (done in #86)
- [x] Add a button that says "contribute with a proposal" that points at the top folder CONTRIBUTING.md (done in #86 )
- [x] remove `Table of Contents` from main README.md (done in #82)
- [x] In the navbar, change `Date` to `Release date`. (done in #85)
- [x] When clicking on sections in the TOC, it would be good if the section would not disappear under the nav bar. (Proposed solution: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) (done in #94: https://arm-software.github.io/acle/mve_intrinsics/mve.html#extract-one-element-from-vector  )
- [x] Add a button to go back to the table of contents in the renderings of the specs (done in #118 )

**Comment by fpetrogalli** [comment]
We can close this issue as all the items in the task list have been addressed.
